### ISSUE TITLE
When a test or test class fails to setup, a java.util.EmptyStackException is thrown and the successful test count is invalid

### ISSUE THREAD

**Issue by jpopadak** [testpackage/testpackage#41]
I don't know if this is specifically related to using Spock and Spring (havent been able to find the cause of reproduction), but this failure happens at _least once_ and I've seen it occur up to 16 times in one test run (46 tests running total with 13 Spock test specifications).

I have noted that this does not occur (or not as often) when using `--quiet` to disable all output from the `ColouredOutputRunListener`.

```
java.util.Stack.peek(Stack.java:102)
org.testpackage.streams.StreamCapture.applyToSystemStreams(StreamCapture.java:94)
org.testpackage.streams.StreamCapture.restore(StreamCapture.java:78)
org.testpackage.ColouredOutputRunListener.testFinished(ColouredOutputRunListener.java:140)
org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
org.spockframework.runtime.JUnitSupervisor.afterFeature(JUnitSupervisor.java:186)
org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:239)
org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:188)
org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:98)
org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
org.junit.runners.Suite.runChild(Suite.java:128)
org.junit.runners.Suite.runChild(Suite.java:27)
org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
org.junit.runners.ParentRunner.run(ParentRunner.java:363)
org.testpackage.junitcore.FailFastSupportCore.run(FailFastSupportCore.java:35)
org.testpackage.junitcore.FailFastSupportCore.run(FailFastSupportCore.java:26)
org.testpackage.TestPackage.run(TestPackage.java:162)
org.testpackage.TestPackage.doMain(TestPackage.java:99)
org.testpackage.TestPackage.main(TestPackage.java:68)
```

**Comment by jpopadak** [comment]
This seems to occur when the `StreamCapture` / `ColouredOutputRunListener` is not catching all scenarios that can occur with tests. A really easy way to reproduce this is by running TestPackage with the following test.

```
public class TestClassSetupFailure {

    @BeforeClass
    public static void beforeClass() {
        throw new IllegalArgumentException();
    }

    @Test
    public void asdf() {
       // Do Nothing
    }
}
```

**Comment by jpopadak** [comment]
I personally do not know the best way to solve this as I have never dealt with Gradle before (nor do I use it). This would be something for @rnorth to work on to prevent errors like the following: 
```
Test mechanism:
      EmptyStackException: 
             At java.util.Stack.peek(Stack.java:102)
```

causing test failure messages like the following: 
```
*** TESTS COMPLETE
*** -1 passed, 1 failed, 0 ignored
```

**Comment by rnorth** [comment]
@jpopadak thanks for raising this and the other PR. I think you're right;
this error is due to something uncaught outside of the main test method.
I'll have a look this weekend and should hopefully have a solution for you.

Richard
On Fri, 20 Jan 2017 at 15:20, jpopadak <notifications@github.com> wrote:

I personally do not know the best way to solve this as I have never dealt
with Gradle before (nor do I use it). This would be something for @rnorth
<https://github.com/rnorth> to work on to prevent errors like the following:

Test mechanism:
      EmptyStackException:
             At java.util.Stack.peek(Stack.java:102)

causing test failure messages like the following:

*** TESTS COMPLETE
*** -1 passed, 1 failed, 0 ignored

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/testpackage/testpackage/issues/41#issuecomment-274097312>,
or mute the thread
